update: add python 3.13 support
Yelp/detect-secrets pull request #900
Opened 2024-12-18 07:07 UTC by clintonsteiner

* **Please check if the PR fulfills these requirements**
- [ X] Tests for the changes have been added

- [X ] Docs have been added / updated

- [ X] All CI checks are green

* **What kind of change does this PR introduce?**

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?**

* **Other information**:

2024-12-20 17:43 UTC, jpdakran requested changes
Looks good to me. Can you update the tox.ini as well with py3.13

2024-12-20 18:39 UTC, clintonsteiner commented
> Looks good to me. Can you update the tox.ini as well with py3.13

Done. Thanks for the review!

2025-01-06 19:51 UTC, clintonsteiner commented
Foce pushed to retrigger run of cicd

2025-01-06 20:28 UTC, jpdakran commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
Can this be removed now?

2025-01-06 20:32 UTC, clintonsteiner commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
Looking

2025-01-06 20:32 UTC, clintonsteiner commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
The add-trailing-comma hook? Yes I can add that in

2025-01-06 20:35 UTC, clintonsteiner commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
Done @jpdakran

2025-01-06 20:41 UTC, jpdakran commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
Sorry, I was referring to the duplicated autopep8 repo. Looks like you got that. If we can keep trailing-comma hook that would be great if possible.

2025-01-06 20:47 UTC, clintonsteiner commented on .pre-commit-config.yaml
>  -   repo: https://github.com/pre-commit/mirrors-autopep8
Fixed

2025-01-06 20:50 UTC, clintonsteiner commented
@jpdakran should I update the CHANGELOG as well? Looks like that is stale now

2025-01-06 20:52 UTC, jpdakran commented
@clintonsteiner We'll get that updated on next release 👍

2025-01-06 20:56 UTC, clintonsteiner commented
@jpdakran  in that case just need you to validate requested change is fixed and merge this in
Would you like a squash?

2025-01-06 20:58 UTC, jpdakran approved these changes

2025-01-06 20:58 UTC, merged